name = "dsbdao"
main = "src/index.ts"
compatibility_date = "2023-02-07"

d1_databases = [
  { binding = "DB", database_name = "dsbdao", database_id = "53f0a894-5868-49e7-aa98-47821c889f5c" }
]

[env.staging]
d1_databases = [
  { binding = "DB", database_name = "dsbdao-staging", database_id = "6f3f2367-7189-49fe-8771-5e11671f83f0" }
]

[env.dev]
workers_dev = true
d1_databases = [
  { binding = "DB", database_name = "dsbdao-dev", database_id = "5e81fde8-273f-4350-9dee-2f0dbb2ab19f", preview_database_id = "5e81fde8-273f-4350-9dee-2f0dbb2ab19f" }
]
